// Paca injects the caller's API key. No integration or worker credential is exposed here.
type Context={pluginId:string;baseURL:string;apiKey:string};
const ids={project_id:{type:"string",description:"项目 UUID"},task_id:{type:"string",description:"任务 UUID"}};
const tools=[
 {name:"tasknotes_get_recurrence",description:"查询任务循环规则、精确时间和下一期清单。",inputSchema:{type:"object",properties:ids,required:["project_id","task_id"]}},
 {name:"tasknotes_set_recurrence",description:"为现有任务配置循环。先查询规则取得来源连接和任务版本；只有一个服务器协调者。支持每日、每周、每月、每年。开始时间只含日期时不生成午夜提醒。空规则停止系列。",inputSchema:{type:"object",properties:{...ids,connection_id:{type:"string"},revision:{type:"integer",minimum:1},op_id:{type:"string",description:"重试必须复用相同操作 ID 和内容"},recurrence:{type:"string"},recurrence_anchor:{type:"string",enum:["scheduled","completion"]},scheduled:{type:"string"},due:{type:"string"}},required:["project_id","task_id","connection_id","revision","op_id","recurrence","recurrence_anchor","scheduled"]}}
];
async function call(context:Context,path:string,method="GET",body?:unknown){const r=await fetch(context.baseURL.replace(/\/$/,"")+"/api/v1"+path,{method,headers:{"X-API-Key":context.apiKey,"Content-Type":"application/json"},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(15000),redirect:"error"});if(!r.ok)throw new Error(`操作未被授权或任务需要核对（${r.status}）。`);return r.json()}
export default{tools,async handleToolCall(name:string,args:Record<string,unknown>,context:Context){try{const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;if(!uuid.test(String(args.project_id))||!uuid.test(String(args.task_id)))throw new Error("项目和任务标识无效。");const core=`/projects/${args.project_id}/tasks/${args.task_id}`;await call(context,core);const route=`/plugins/${context.pluginId}${core}/recurrence`;let result;if(name==="tasknotes_get_recurrence")result=await call(context,route);else if(name==="tasknotes_set_recurrence")result=await call(context,route,"PUT",args);else throw new Error("未知循环操作。");return{content:[{type:"text",text:JSON.stringify(result)}]}}catch(e){return{isError:true,content:[{type:"text",text:e instanceof Error?e.message:"循环操作失败。"}]}}}};
