import {useEffect,useState,type ReactNode} from "react";
import HistoryCleanup,{type HistorySelection} from "./HistoryCleanup";
import {Card,CardHeader,CardTitle,CardDescription,CardContent} from "./components/ui/card";
import {Button} from "./components/ui/button";
import {Badge} from "./components/ui/badge";
export type Delivery={id:number;delivery_id:string;event:string;state:string;error:string;received_at:string;path?:string;title?:string};
export type Source={id:number;path:string;task_id:string;state:string;verified_at?:string;verification_error?:string};
const states:Record<string,string>={linked:"已关联",superseded:"已替代",link_pending:"待核对关联",creating:"正在创建",pending:"待处理",applied:"已同步",active:"已关联",deleted:"失效",archived:"已归档",stale:"旧事件已忽略",conflict:"待解决冲突",error:"处理失败",uncertain:"创建待核对",unassociated:"待关联"};
const events:Record<string,string>={"task.created":"创建任务","task.updated":"更新任务","task.completed":"完成任务","task.deleted":"删除任务","task.archived":"归档任务","task.unarchived":"取消归档","recurring.instance.completed":"完成本期","recurring.instance.skipped":"跳过本期"};
export default function HistoryRecords({base,projectId,deliveries,sources,signatureFailures,verificationPending,canEdit,onComplete,children}:{base:string;projectId:string;deliveries:Delivery[];sources:Source[];signatureFailures:number;verificationPending:boolean;canEdit:boolean;onComplete:()=>Promise<void>;children:ReactNode}){
 const [eventIDs,setEventIDs]=useState<number[]>([]),[sourceIDs,setSourceIDs]=useState<number[]>([]),[selection,setSelection]=useState<HistorySelection|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const eligibleEvents=deliveries.filter(d=>d.state!=="pending"),eligibleSources=sources.filter(s=>["deleted","superseded"].includes(s.state));
 useEffect(()=>{setEventIDs(ids=>ids.filter(id=>deliveries.some(d=>d.id===id&&d.state!=="pending")))},[deliveries]);
 useEffect(()=>{setSourceIDs(ids=>ids.filter(id=>sources.some(s=>s.id===id&&["deleted","superseded"].includes(s.state))))},[sources]);
 async function act(path:string){setBusy(true);setError("");try{const r=await fetch(base+path,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:"{}"});if(!r.ok){const v=await r.json();throw Error(typeof v.error==="string"?v.error:v.error?.message??"操作暂未完成，请稍后重试。")}await onComplete()}catch(e){setError(e instanceof Error?e.message:"操作暂未完成。")}finally{setBusy(false)}}
 function toggle(ids:number[],id:number){return ids.includes(id)?ids.filter(x=>x!==id):[...ids,id]}
 const disabled=busy||!canEdit||!!selection;
 return <>
 <HistoryCleanup base={base} canEdit={canEdit} selection={selection} onSelectionHandled={()=>setSelection(null)} onComplete={onComplete}/>
 {error&&<p role="alert" className="text-sm text-destructive">{error}</p>}
 <details className="sync-details" data-testid="receive-history"><summary>接收历史 · {deliveries.length}</summary><Card><CardHeader><CardTitle>接收历史</CardTitle><CardDescription>{signatureFailures?`有 ${signatureFailures} 次签名验证未通过，请核对密钥。`:deliveries.length?"选择旧冲突后，可丢弃对应未同步变更。":"尚未收到任务事件。"}</CardDescription></CardHeader><CardContent className="grid gap-3">
 {eligibleEvents.length>0&&<div className="sync-history-selection"><label><input type="checkbox" aria-label="选择全部可清理接收记录" checked={eventIDs.length===eligibleEvents.length} disabled={disabled} onChange={e=>setEventIDs(e.target.checked?eligibleEvents.map(d=>d.id):[])}/>全选可清理记录</label>{eventIDs.length>0&&<Button variant="destructive" disabled={disabled} onClick={()=>setSelection({mode:"events",ids:eventIDs})}>清理选中接收记录（{eventIDs.length}）</Button>}</div>}
 {deliveries.map(d=><div key={d.id} data-testid={`delivery-row-${d.id}`} className="grid gap-2 rounded-lg border p-3 text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><label className="sync-history-row-label"><input type="checkbox" aria-label={`选择接收记录 ${d.id}`} checked={eventIDs.includes(d.id)} disabled={disabled||d.state==="pending"} onChange={()=>setEventIDs(ids=>toggle(ids,d.id))}/><strong>{d.title||events[d.event]||"任务变更"}</strong></label><Badge variant={d.state==="error"||d.state==="conflict"?"destructive":"secondary"}>{states[d.state]??"正在核对"}</Badge></div>{d.path&&<p className="break-all text-muted-foreground">{d.path}</p>}<p className="text-muted-foreground">{new Date(d.received_at).toLocaleString("zh-CN")}</p>{d.error&&<p className="text-muted-foreground">{d.state==="conflict"?"任务两次变更存在冲突，可重新核对或丢弃这次变更。":d.state==="uncertain"?"创建结果尚未确认，请先核对已有任务。":"任务尚未同步，请核对连接与状态映射后重试。"}</p>}<div className="sync-actions">{['conflict','uncertain','error'].includes(d.state)&&<Button variant="outline" disabled={disabled} onClick={()=>void act(`/reprocess/${encodeURIComponent(d.delivery_id)}`)}>重新核对</Button>}{d.state!=="pending"&&<Button variant="outline" disabled={disabled} onClick={()=>setSelection({mode:"events",ids:[d.id]})}>清理</Button>}</div></div>)}
 </CardContent></Card></details>
 <details className="sync-details" data-testid="source-history"><summary>来源关联 · {sources.length}</summary><Card><CardHeader><CardTitle>来源关联</CardTitle><CardDescription>核验对应任务后，已删除任务的关联会标为失效。</CardDescription></CardHeader><CardContent className="grid gap-3"><div className="sync-actions"><Button variant="outline" disabled={disabled||verificationPending} onClick={()=>void act('/source-recheck')}>{verificationPending?"正在核验来源…":"核验来源"}</Button></div>
 {eligibleSources.length>0&&<div className="sync-history-selection"><label><input type="checkbox" aria-label="选择全部失效关联" checked={sourceIDs.length===eligibleSources.length} disabled={disabled} onChange={e=>setSourceIDs(e.target.checked?eligibleSources.map(s=>s.id):[])}/>全选失效关联</label>{sourceIDs.length>0&&<Button variant="destructive" disabled={disabled} onClick={()=>setSelection({mode:"sources",ids:sourceIDs})}>清理选中失效关联（{sourceIDs.length}）</Button>}</div>}
 {sources.map(s=><div key={s.id} data-testid={`source-row-${s.id}`} className="grid gap-2 rounded-lg border p-3 text-sm"><div className="flex flex-wrap items-center gap-2"><label className="sync-history-row-label"><input type="checkbox" aria-label={`选择来源关联 ${s.id}`} checked={sourceIDs.includes(s.id)} disabled={disabled||!["deleted","superseded"].includes(s.state)} onChange={()=>setSourceIDs(ids=>toggle(ids,s.id))}/><strong className="break-all">{s.path}</strong></label><Badge variant="secondary">{states[s.state]??"正在核对"}</Badge>{s.task_id&&!["deleted","superseded"].includes(s.state)&&<a className="text-primary underline" href={`/projects/${projectId}/tasks/${s.task_id}`}>打开任务</a>}{["deleted","superseded"].includes(s.state)&&<Button variant="outline" disabled={disabled} onClick={()=>setSelection({mode:"sources",ids:[s.id]})}>清理失效关联</Button>}</div>{s.verification_error&&<p role="status" className="text-muted-foreground">{s.verification_error}</p>}</div>)}
 {children}</CardContent></Card></details>
 </>;
}
