import {useEffect,useRef,useState} from "react";
import {Button} from "./components/ui/button";
type Summary={deleted_tasks:number;processed_events:number;obsolete_sources:number;cutoff:string;live_changes:number};
export type HistorySelection={mode:"events"|"sources";ids:number[]};
export default function HistoryCleanup({base,canEdit,onComplete,selection,onSelectionHandled}:{base:string;canEdit:boolean;onComplete:()=>Promise<void>;selection?:HistorySelection|null;onSelectionHandled?:()=>void}){
 const [reviewed,setReviewed]=useState<HistorySelection|null>(null);
 const [summary,setSummary]=useState<Summary|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(summary)dialog.current?.showModal();else dialog.current?.close()},[summary]);
 async function call(method="GET",body?:unknown,preview=false){const r=await fetch(base+(preview?"/history-cleanup-preview":"/history-cleanup"),{method,credentials:"include",headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(typeof data.error==="string"?data.error:data.error?.message??data.message??"旧历史暂时无法清理。");return data;}
 async function review(picked:HistorySelection|null=null){setBusy(true);setReviewed(picked);setError("");setMessage("");try{setSummary(await call(picked?"POST":"GET",picked??undefined,!!picked))}catch(e){setError(e instanceof Error?e.message:"无法读取清理范围。");onSelectionHandled?.()}finally{setBusy(false)}}
 useEffect(()=>{if(selection)void review(selection)},[selection]);
 function close(){setSummary(null);onSelectionHandled?.()}
 async function refresh(){setBusy(true);setError("");try{await onComplete()}catch(e){setError(e instanceof Error?e.message:"暂时无法刷新。")}finally{setBusy(false)}}
 async function clear(){if(!summary)return;setBusy(true);setError("");try{const r:Summary=await call("POST",{...reviewed,cutoff:summary.cutoff,confirm:true});close();const remaining=reviewed?reviewed.ids.length-Number(reviewed.mode==="events"?r.processed_events:r.obsolete_sources):0;setMessage((reviewed?.mode==="events"?`已清理 ${r.processed_events} 条接收记录。`:reviewed?.mode==="sources"?`已清理 ${r.obsolete_sources} 条失效关联及 ${r.processed_events} 条接收记录。`:`已清理 ${r.deleted_tasks} 条已删除任务历史、${r.processed_events} 条接收记录和 ${r.obsolete_sources} 条失效关联。`)+(remaining>0?"其余记录已变化或正在处理，请刷新后核对。":""));await onComplete()}catch(e){setError(e instanceof Error?e.message:"旧历史暂时无法清理。")}finally{setBusy(false)}}
 const count=summary?Number(summary.deleted_tasks)+Number(summary.processed_events)+Number(summary.obsolete_sources):0;
 const title=reviewed?.mode==="events"?"清理接收记录":reviewed?.mode==="sources"?"清理失效关联":"清理旧历史";
 const eligible=summary&&reviewed?Number(reviewed.mode==="events"?summary.processed_events:summary.obsolete_sources):0;
 return <div className="grid gap-2"><div className="sync-actions"><Button variant="outline" disabled={!canEdit||busy} onClick={()=>void review()}>清理旧历史</Button><Button variant="outline" disabled={busy} onClick={()=>void refresh()}>刷新记录</Button></div>{message&&<p role="status" className="text-sm">{message}</p>}{error&&!summary&&<p role="alert" className="text-sm text-destructive">{error}</p>}
  <dialog ref={dialog} className="sync-history-dialog" aria-labelledby="history-cleanup-title" onCancel={e=>{e.preventDefault();if(!busy)close()}}><h2 id="history-cleanup-title">{title}</h2>{summary&&<><p className="text-sm">{count?"将清理以下记录，详情清理后无法恢复。":"所选记录已变化或正在处理，当前无法清理。"}</p><ul className="sync-cleanup-counts"><li>已删除任务历史 <strong>{summary.deleted_tasks}</strong></li><li>接收记录 <strong>{summary.processed_events}</strong></li><li>失效来源关联 <strong>{summary.obsolete_sources}</strong></li></ul>{reviewed&&eligible<reviewed.ids.length&&<p className="text-sm">所选 {reviewed.ids.length} 条中有 {reviewed.ids.length-eligible} 条暂不可清理，将保留。</p>}{reviewed?.mode==="events"&&summary.live_changes>0&&<p role="note" className="text-sm">将放弃 {summary.live_changes} 次尚未同步到有效任务的变更，任务当前内容保留。</p>}<p className="text-sm text-muted-foreground">现有任务、本地笔记、照片和防重复同步标记保留。{reviewed?"对应排队变更会一并丢弃，正在处理的记录保留。":"正在处理的记录与有效任务冲突保留。"}</p></>}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<div className="sync-dialog-actions"><Button variant="outline" autoFocus disabled={busy} onClick={close}>取消</Button><Button variant="destructive" disabled={busy||!count} onClick={()=>void clear()}>{busy?"正在清理…":"确认清理"}</Button></div></dialog>
 </div>
}
