import {useEffect,useRef,useState} from "react";
import {Button} from "./components/ui/button";
type Summary={deleted_tasks:number;processed_events:number;obsolete_sources:number;cutoff:string};
export default function HistoryCleanup({base,canEdit,onComplete}:{base:string;canEdit:boolean;onComplete:()=>Promise<void>}){
 const [summary,setSummary]=useState<Summary|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(summary)dialog.current?.showModal();else dialog.current?.close()},[summary]);
 async function call(method="GET",body?:unknown){const r=await fetch(base+"/history-cleanup",{method,credentials:"include",headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(typeof data.error==="string"?data.error:data.error?.message??data.message??"旧历史暂时无法清理。");return data;}
 async function review(){setBusy(true);setError("");setMessage("");try{setSummary(await call())}catch(e){setError(e instanceof Error?e.message:"无法读取清理范围。")}finally{setBusy(false)}}
 async function clear(){if(!summary)return;setBusy(true);setError("");try{const r:Summary=await call("POST",{cutoff:summary.cutoff,confirm:true});setSummary(null);setMessage(`已清理 ${r.deleted_tasks} 条已删除任务历史、${r.processed_events} 条接收记录和 ${r.obsolete_sources} 条失效关联。`);await onComplete()}catch(e){setError(e instanceof Error?e.message:"旧历史暂时无法清理。")}finally{setBusy(false)}}
 const count=summary?Number(summary.deleted_tasks)+Number(summary.processed_events)+Number(summary.obsolete_sources):0;
 return <div className="grid gap-2"><div className="sync-actions"><Button variant="outline" disabled={!canEdit||busy} onClick={()=>void review()}>清理旧历史</Button><span className="text-sm text-muted-foreground">仅清理当前连接的旧记录</span></div>{message&&<p role="status" className="text-sm">{message}</p>}{error&&!summary&&<p role="alert" className="text-sm text-destructive">{error}</p>}
  <dialog ref={dialog} className="sync-history-dialog" aria-labelledby="history-cleanup-title" onCancel={e=>{e.preventDefault();if(!busy)setSummary(null)}}><h2 id="history-cleanup-title">清理旧历史</h2>{summary&&<><p className="text-sm">{count?"将清理以下记录，详情清理后无法恢复。":"当前没有可清理的旧历史。"}</p><ul className="sync-cleanup-counts"><li>已删除任务历史 <strong>{summary.deleted_tasks}</strong></li><li>已处理或失效的接收记录 <strong>{summary.processed_events}</strong></li><li>失效来源关联 <strong>{summary.obsolete_sources}</strong></li></ul><p className="text-sm text-muted-foreground">现有任务、本地笔记、照片和防重复同步标记保留。正在处理的记录与有效任务冲突保留。</p></>}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<div className="sync-dialog-actions"><Button variant="outline" autoFocus disabled={busy} onClick={()=>setSummary(null)}>取消</Button><Button variant="destructive" disabled={busy||!count} onClick={()=>void clear()}>{busy?"正在清理…":"确认清理"}</Button></div></dialog>
 </div>
}
