import SyncSettings from "./SyncSettings";
import HistoryRecords,{type Delivery,type Source} from "./HistoryRecords";
import {useCallback,useEffect,useState,useRef} from "react";
import {Card,CardHeader,CardTitle,CardDescription,CardContent} from "./components/ui/card";
import {Button} from "./components/ui/button";import {Input} from "./components/ui/input";import {Label} from "./components/ui/label";import {Switch} from "./components/ui/switch";import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "./components/ui/select";import "./theme.css";
const ID="com.selfcommand.tasknotes-webhook";
const userError=(value:unknown)=>value instanceof Error && /^[\u4e00-\u9fff]/.test(value.message)?value.message:"暂时无法连接，请稍后重试。";
type Connection={id:string;name:string;enabled:boolean;timezone:string;status_map:Record<string,string>;priority_map:Record<string,number>;revision:number;archive_tag?:string};
type Task={id:string;title:string;task_number:number};
const names:Record<string,string>={Todo:"待完成","In Progress":"进行中",Done:"已完成",Backlog:"待安排",Archive:"已归档"};
const defaults:Record<string,string>={open:"待完成","in-progress":"进行中",done:"已完成","@completed":"完成事件","@archived":"归档事件"};
async function response<T>(url:string,method="GET",body?:unknown):Promise<T>{const r=await fetch(url,{method,credentials:"include",headers:{"Content-Type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(typeof data.error==="string"?data.error:data.error?.message??data.message??"暂时无法连接，请稍后重试。");return data}
const api=<T,>(path:string,method="GET",body?:unknown)=>response<T>(`/api/v1/plugins/${ID}${path}`,method,body);
export default function SettingsTab({projectId,canEdit=true}:{projectId:string;canEdit?:boolean}){
 const [verificationPending,setVerificationPending]=useState(false);const autoPick=useRef(false);const[refreshKey,setRefreshKey]=useState(0);
 const base=`/projects/${encodeURIComponent(projectId)}`;const[connections,setConnections]=useState<Connection[]>([]);const[selected,setSelected]=useState<Connection|null>(null);const[deliveries,setDeliveries]=useState<Delivery[]>([]);const[sources,setSources]=useState<Source[]>([]);const[name,setName]=useState("TaskNotes 桌面端");const[timezone,setTimezone]=useState("Asia/Shanghai");const[statusMap,setStatusMap]=useState<Record<string,string>>({});const[priorityMap,setPriorityMap]=useState<Record<string,number>>({low:10,normal:35,high:75});const[archiveTag,setArchiveTag]=useState("archived");const[projectStatuses,setProjectStatuses]=useState<{id:string;name:string;category:string}[]>([]);const[signatureFailures,setSignatureFailures]=useState(0);const[enabled,setEnabled]=useState(true);const[senderSecret,setSenderSecret]=useState("");const[state,setState]=useState("正在连接…");const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[credential,setCredential]=useState<{secret:string;receive_url?:string}|null>(null);const[sourceID,setSourceID]=useState("");const[taskID,setTaskID]=useState("");const[tasks,setTasks]=useState<Task[]>([]);const[taskPage,setTaskPage]=useState(1);const[hasMore,setHasMore]=useState(false);const[customStatus,setCustomStatus]=useState("");
 const load=useCallback(async()=>{const [r,ps]=await Promise.all([api<{items:Connection[]}>(`${base}/connections`),response<{data:{items:typeof projectStatuses}}>(`/api/v1${base}/task-statuses`)]);setConnections(r.items);setProjectStatuses(ps.data.items);setState("已连接")},[base]);
 const history=useCallback(async(id:string)=>{const[d,s]=await Promise.all([api<{items:Delivery[];diagnostics?:{signature_failures:number}}>(`${base}/connections/${id}/deliveries`),api<{items:Source[];verification_pending:number}>(`${base}/connections/${id}/sources`)]);setDeliveries(d.items);setSignatureFailures(d.diagnostics?.signature_failures??0);setSources(s.items);setVerificationPending(Number(s.verification_pending??0)>0)},[base]);
 useEffect(()=>{let active=true;load().catch(e=>{if(active)setError(userError(e))});return()=>{active=false;setCredential(null)}},[load]);useEffect(()=>{if(!selected)return;history(selected.id).catch(e=>setError(userError(e)));if(!verificationPending&&!deliveries.some(d=>d.state==="pending"))return;const timer=setInterval(()=>history(selected.id).catch(e=>setError(userError(e))),verificationPending?2000:10000);return()=>clearInterval(timer)},[selected?.id,history,verificationPending,deliveries.some(d=>d.state==="pending")]);
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError("");try{await fn()}catch(e){setError(userError(e))}finally{setBusy(false)}};
 function choose(c:Connection|null){setSelected(c);setCredential(null);setSenderSecret("");setArchiveTag(c?.archive_tag??"archived");setName(c?.name??"TaskNotes 桌面端");setTimezone(c?.timezone??"Asia/Shanghai");setEnabled(c?.enabled??true);setStatusMap(c?.status_map??{});setPriorityMap(c?.priority_map??{low:10,normal:35,high:75});setSourceID("");setTaskID("");setTasks([]);setTaskPage(1);setHasMore(false)}
 useEffect(()=>{if(autoPick.current||connections.length===0)return;autoPick.current=true;if(connections.length===1)choose(connections[0])},[connections]);
 const config=()=>({name,timezone,enabled,status_map:Object.fromEntries(Object.entries(statusMap).filter(([,value])=>value!=="")),priority_map:priorityMap,revision:selected?.revision,secret:senderSecret.trim()||undefined,archive_tag:archiveTag});
 async function loadTasks(page=1){const r=await response<{data:{items:Task[]}}>(`/api/v1${base}/tasks?page=${page}&page_size=100`);setTasks(old=>page===1?r.data.items:[...old,...r.data.items.filter(t=>!old.some(o=>o.id===t.id))]);setTaskPage(page);setHasMore(r.data.items.length===100)}
 return <section className="checkin-ui grid gap-5 p-4"><Card><CardHeader><CardTitle>TaskNotes 接入</CardTitle><CardDescription role="status">{state}</CardDescription></CardHeader><CardContent className="grid gap-4">{error&&<p role="alert" className="rounded-lg border border-destructive/30 p-3 text-sm text-destructive">{error}</p>}
 <Label className="grid min-w-0 gap-2">项目连接<Select value={selected?.id??"new"} onValueChange={id=>choose(connections.find(c=>c.id===id)??null)}><SelectTrigger aria-label="项目连接"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="new">新建连接</SelectItem>{connections.map(c=><SelectItem key={c.id} value={c.id}>{c.name}{c.enabled?"":"（停用）"}</SelectItem>)}</SelectContent></Select></Label>
 <details className="sync-details" open={!selected}><summary>{selected?"连接设置":"创建连接"}</summary><div className="sync-details-body grid gap-4"><p className="text-sm text-muted-foreground">创建连接后，将接收地址粘贴到桌面端 TaskNotes 的网络钩子设置，再将其生成的签名密钥填回此处。订阅创建、更新、完成、删除、归档与取消归档六种任务事件。手机端不会发送这些事件，离线时未送达的事件也不会自动补齐。</p>
 <div className="grid gap-3 sm:grid-cols-2"><Label className="grid min-w-0 gap-2">连接名称<Input value={name} onChange={e=>setName(e.target.value)}/></Label><Label className="grid min-w-0 gap-2">时区<Input value={timezone} onChange={e=>setTimezone(e.target.value)}/></Label></div>{selected&&<><Label><Switch checked={enabled} onCheckedChange={setEnabled}/> 启用接收和导入</Label><Label className="grid min-w-0 gap-2">接收地址<Input readOnly value={`${location.origin}/api/v1/plugins/${ID}/receive/${selected.id}`}/></Label><Button variant="outline" onClick={()=>act(async()=>navigator.clipboard.writeText(`${location.origin}/api/v1/plugins/${ID}/receive/${selected.id}`))}>复制接收地址</Button></>}
 <Label className="grid min-w-0 gap-2">签名密钥（TaskNotes Secret）<Input aria-label="签名密钥（TaskNotes Secret）" type="password" autoComplete="new-password" spellCheck={false} value={senderSecret} onChange={e=>setSenderSecret(e.target.value)} placeholder={selected?"粘贴新的密钥；留空保留原值":"粘贴 TaskNotes 生成的密钥"}/></Label><p className="text-xs text-muted-foreground">密钥加密保存，保存后不重新显示。更换密钥不影响任务和历史记录。</p><Label className="grid min-w-0 gap-2">TaskNotes 归档标签<Input aria-label="TaskNotes 归档标签" value={archiveTag} onChange={e=>setArchiveTag(e.target.value)}/></Label>
 <div className="grid gap-3 sm:grid-cols-2">{[...new Set([...Object.keys(defaults),...Object.keys(statusMap)])].map(key=><Label className="grid min-w-0 gap-2" key={key}>{key==="@archived"?"归档状态":`${defaults[key]??key}对应状态`}<Select value={statusMap[key]||"auto"} onValueChange={value=>{const next={...statusMap};if(value==="auto")delete next[key];else next[key]=value;setStatusMap(next)}}><SelectTrigger aria-label={key==="@archived"?"归档状态":undefined}><SelectValue placeholder="选择项目状态"/></SelectTrigger><SelectContent><SelectItem value="auto">{key==="@archived"?"请选择归档状态":"自动匹配"}</SelectItem>{projectStatuses.map(s=><SelectItem key={s.id} value={s.id}>{names[s.name]??s.name}</SelectItem>)}</SelectContent></Select></Label>)}</div>
 <div className="flex flex-wrap gap-2"><Input aria-label="自定义 TaskNotes 状态" placeholder="添加自定义 TaskNotes 状态值" value={customStatus} onChange={e=>setCustomStatus(e.target.value)}/><Button variant="outline" disabled={!customStatus.trim()||customStatus.startsWith("@")} onClick={()=>{setStatusMap({...statusMap,[customStatus.trim()]:statusMap[customStatus.trim()]??""});setCustomStatus("")}}>添加状态映射</Button></div>
 <div className="grid gap-3 sm:grid-cols-3">{([['low','低优先级'],['normal','普通优先级'],['high','高优先级']] as const).map(([key,label])=><Label className="grid min-w-0 gap-2" key={key}>{label}<Input type="number" min="0" max="100" value={priorityMap[key]??0} onChange={e=>setPriorityMap({...priorityMap,[key]:Number(e.target.value)})}/></Label>)}</div><p className="text-xs text-muted-foreground">对应 Paca 的重要度，数值越大优先级越高。</p>
 <Button disabled={busy||!canEdit} onClick={()=>act(async()=>{if(selected){const r=await api<{revision:number}>(`${base}/connections/${selected.id}`,"PATCH",config());choose({...selected,name,timezone,enabled,status_map:statusMap,priority_map:priorityMap,revision:r.revision,archive_tag:archiveTag})}else{const r=await api<{id:string;revision:number;secret:string;receive_url:string}>(`${base}/connections`,"POST",config());const provided=senderSecret.trim()!=="";choose({id:r.id,revision:r.revision,name,timezone,enabled:true,status_map:statusMap,priority_map:priorityMap,archive_tag:archiveTag});if(!provided)setCredential(r)}await load()})}>{selected?"保存连接":"创建连接"}</Button>{credential&&<div className="grid gap-2 rounded-lg border p-3"><p className="text-sm">连接已创建。请复制接收地址到 TaskNotes，再将其生成的签名密钥填写到上方保存。</p><Button variant="outline" onClick={()=>setCredential(null)}>知道了</Button></div>}</div></details></CardContent></Card>
 {selected&&<><SyncSettings projectId={projectId} connectionId={selected.id} canEdit={canEdit} refreshKey={refreshKey}/><HistoryRecords key={selected.id} base={`/api/v1/plugins/${ID}${base}/connections/${selected.id}`} projectId={projectId} deliveries={deliveries} sources={sources} signatureFailures={signatureFailures} verificationPending={verificationPending} canEdit={canEdit} onComplete={async()=>{await history(selected.id);setRefreshKey(k=>k+1)}}>
 <Label className="grid min-w-0 gap-2">待关联笔记<Select value={sourceID} onValueChange={setSourceID}><SelectTrigger><SelectValue placeholder="请选择来源笔记"/></SelectTrigger><SelectContent>{sources.filter(s=>!["deleted","superseded"].includes(s.state)).map(s=><SelectItem key={s.id} value={String(s.id)}>{s.path}</SelectItem>)}</SelectContent></Select></Label><Button variant="outline" disabled={busy} onClick={()=>act(()=>loadTasks())}>加载项目任务</Button>{tasks.length>0&&<Label className="grid min-w-0 gap-2">对应 Paca 任务<Select value={taskID} onValueChange={setTaskID}><SelectTrigger><SelectValue placeholder="请选择已确认的对应任务"/></SelectTrigger><SelectContent>{tasks.map(t=><SelectItem key={t.id} value={t.id}>#{t.task_number} {t.title}</SelectItem>)}</SelectContent></Select></Label>}{hasMore&&<Button variant="outline" disabled={busy} onClick={()=>act(()=>loadTasks(taskPage+1))}>加载更多任务</Button>}<Button disabled={busy||!canEdit||!sourceID||!taskID} onClick={()=>act(async()=>{await api(`${base}/connections/${selected.id}/link`,"POST",{source_id:Number(sourceID),task_id:taskID});await history(selected.id)})}>确认关联并核对</Button></HistoryRecords></>}
 </section>;
}
