import {useEffect,useState} from "react";
import {Card,CardHeader,CardTitle,CardContent} from "./components/ui/card";
import {Input} from "./components/ui/input";
import {Button} from "./components/ui/button";
import {Badge} from "./components/ui/badge";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "./components/ui/select";
type Item={sync_id:string;snapshot:{title?:string};warning:string;path:string};
type Preview={items:Item[];total:number;history_items:Item[];history_total:number;ready:boolean;warning_count:number;scan_error:string};
type Connection={id:string;recurrence_enabled:boolean;task_tag:string;sync_mode:string;revision:number;reverse_status_map:Record<string,string>;status_map:Record<string,string>};
const labels:Record<string,string>={Todo:"待完成","In Progress":"进行中",Done:"已完成",Backlog:"待安排",Archive:"归档",open:"待完成","in-progress":"进行中",done:"已完成",cancelled:"已取消"};
async function request(path:string,method="GET",body?:unknown){const r=await fetch(path,{method,credentials:"include",headers:{"Content-Type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(typeof data.error==="string"?data.error:data.error?.message??data.message??"暂时无法连接，请稍后重试。");return data;}
export default function SyncSettings({projectId,connectionId,canEdit,refreshKey=0}:{projectId:string;connectionId:string;canEdit:boolean;refreshKey?:number}){
 const [mode,setMode]=useState("off"),[recurrence,setRecurrence]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[token,setToken]=useState(""),[taskTag,setTaskTag]=useState("task");
 const [preview,setPreview]=useState<Preview>({items:[],total:0,history_items:[],history_total:0,ready:false,warning_count:0,scan_error:""});
 const [statuses,setStatuses]=useState<{id:string;name:string}[]>([]),[values,setValues]=useState<string[]>([]),[reverse,setReverse]=useState<Record<string,string>>({});
 const base=`/api/v1/plugins/com.selfcommand.tasknotes-webhook/projects/${projectId}/connections/${connectionId}`;
 async function connection():Promise<Connection>{const all=await request(`/api/v1/plugins/com.selfcommand.tasknotes-webhook/projects/${projectId}/connections`);const c=all.items.find((v:Connection)=>v.id===connectionId);if(!c)throw Error("来源连接未找到。");return c;}
 async function load(){const [c,list,p]=await Promise.all([connection(),request(`/api/v1/projects/${projectId}/task-statuses`),request(base+"/sync-preview")]);setRecurrence(c.recurrence_enabled??false);setTaskTag(c.task_tag??"task");setMode(c.sync_mode??"off");setReverse(c.reverse_status_map??{});setValues(Object.keys(c.status_map??{}).filter(k=>!k.startsWith("@")));setStatuses([{id:"@none",name:"未设置状态"},...list.data.items]);setPreview(p);}
 useEffect(()=>{setToken("");setError("");void load().catch(e=>setError(e.message))},[base,refreshKey]);
 useEffect(()=>{if(mode!=="preview"||preview.ready||preview.scan_error||preview.warning_count)return;const timer=setInterval(()=>{void request(base+"/sync-preview").then(setPreview).catch(e=>setError(e.message))},3000);return()=>clearInterval(timer)},[base,mode,preview.ready,preview.scan_error,preview.warning_count]);
 async function act(fn:()=>Promise<void>){setBusy(true);setError("");try{await fn()}catch(e){setError(e instanceof Error?e.message:"暂时无法操作。")}finally{setBusy(false)}}
 async function setSync(next:string){const c=await connection();await request(base+"/sync-config","PUT",{mode:next,revision:c.revision,reverse_status_map:c.reverse_status_map??{}});await load()}
 return <Card><CardHeader><div className="sync-heading"><CardTitle>双向任务同步</CardTitle><Badge variant="secondary">{mode==="enabled"?"已启用":mode==="preview"?(preview.ready?"清单已准备好":"待确认清单"):"未启用"}</Badge></div></CardHeader><CardContent className="grid gap-4">
  <p className="text-sm text-muted-foreground">Paca 和 Obsidian 同步当前项目的任务。</p>
  <div className="sync-actions">{mode!=="enabled"&&<Button variant="outline" disabled={busy||!canEdit} onClick={()=>act(()=>setSync("preview"))}>{mode==="preview"?"重新准备清单":"准备任务清单"}</Button>}<Button variant="outline" disabled={busy} onClick={()=>act(load)}>刷新清单</Button>{mode==="preview"&&<Button disabled={busy||!canEdit||!preview.ready} onClick={()=>act(()=>setSync("enabled"))}>{preview.total?`启用双向同步（${preview.total} 个任务）`:"启用双向同步"}</Button>}</div>
  {mode==="preview"&&!preview.ready&&!preview.scan_error&&!preview.warning_count&&<p role="status" className="text-sm text-muted-foreground">正在准备清单，完成后可启用同步。</p>}{preview.scan_error&&<p role="alert" className="text-sm text-destructive">{preview.scan_error}</p>}{preview.warning_count>0&&<p role="alert" className="text-sm text-destructive">{preview.warning_count} 个当前任务需要处理下方提示，再重新准备清单。</p>}
  <div className="grid gap-2" aria-label="当前任务清单"><p className="text-sm">当前任务 · {preview.total}</p>{!preview.total&&<p className="text-sm text-muted-foreground">当前没有任务。清单准备完成后仍可启用同步，之后新建的任务会自动加入。</p>}{preview.items.map(item=><div key={item.sync_id} className="sync-task"><strong>{item.snapshot.title||"任务"}</strong><p className="text-sm text-muted-foreground">{item.path||"同步时创建任务笔记"}</p>{item.warning&&<p className="text-sm text-destructive">{item.warning}</p>}</div>)}{preview.total>preview.items.length&&<p className="text-sm text-muted-foreground">显示前 {preview.items.length} 条，同步包含全部 {preview.total} 个任务。</p>}</div>
  {preview.history_total>0&&<details className="sync-details" data-testid="deleted-task-history"><summary>已删除任务历史 · {preview.history_total}</summary><div className="sync-details-body"><p className="text-sm text-muted-foreground">这些记录不计入首次同步清单，可在下方清理旧历史。</p>{preview.history_items.map(item=><div key={item.sync_id} className="sync-task"><strong>{item.snapshot.title||"已删除任务"}</strong><p className="text-sm text-muted-foreground">{item.path}</p></div>)}</div></details>}
  <details className="sync-details"><summary>同步设置与设备配对</summary><div className="sync-details-body grid gap-3"><label className="grid gap-1 text-sm">TaskNotes 任务识别标签<Input value={taskTag} disabled={!canEdit||busy} onChange={e=>setTaskTag(e.target.value)}/></label><p className="text-sm">Paca 状态对应的 TaskNotes 状态</p>{statuses.map(status=><label key={status.id} className="grid grid-cols-2 items-center gap-2 text-sm"><span>{labels[status.name]??status.name}</span><Select value={reverse[status.id]||"automatic"} onValueChange={value=>setReverse(prior=>({...prior,[status.id]:value==="automatic"?"":value}))}><SelectTrigger disabled={!canEdit||busy}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="automatic">沿用唯一对应</SelectItem>{values.map(value=><SelectItem key={value} value={value}>{labels[value]??value}</SelectItem>)}</SelectContent></Select></label>)}
   <div className="sync-actions"><Button variant="outline" disabled={!canEdit||busy} onClick={()=>act(async()=>{const c=await connection();await request(base+"/sync-config","PUT",{mode:c.sync_mode,revision:c.revision,task_tag:taskTag,reverse_status_map:Object.fromEntries(Object.entries(reverse).filter(([,value])=>value))});await load()})}>保存同步设置</Button><Button variant="outline" disabled={!canEdit||busy||mode!=="enabled"} onClick={()=>act(async()=>{const c=await connection();await request(base+"/sync-config","PUT",{mode:c.sync_mode,revision:c.revision,reverse_status_map:c.reverse_status_map??{},recurrence_enabled:!recurrence});await load()})}>{recurrence?"暂停循环排期":"启用循环排期"}</Button>{mode==="enabled"&&<Button variant="outline" disabled={busy||!canEdit} onClick={()=>act(()=>setSync("off"))}>暂停同步</Button>}<Button variant="outline" disabled={busy||!canEdit} onClick={()=>act(async()=>{const r=await request(base+"/pairing","POST",{});setToken(r.token)})}>生成配对码</Button></div>{token&&<div className="sync-task"><p className="text-sm">配对码仅显示本次，可用于同一笔记库的电脑和手机。</p><div className="sync-actions"><Button variant="outline" onClick={()=>act(async()=>navigator.clipboard.writeText(token))}>复制配对码</Button><Button variant="ghost" onClick={()=>setToken("")}>已保存</Button></div></div>}
  </div></details>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}
 </CardContent></Card>
}
