import {useEffect,useState} from "react";
import {Card,CardHeader,CardTitle,CardDescription,CardContent} from "./components/ui/card";
import {Button} from "./components/ui/button";import {Badge} from "./components/ui/badge";
export default function SyncSettings({projectId,connectionId,canEdit}:{projectId:string;connectionId:string;canEdit:boolean}){
 const [mode,setMode]=useState("off"),[revision,setRevision]=useState(0),[items,setItems]=useState<{sync_id:string;snapshot:{title:string};warning:string;deleted:boolean;path:string}[]>([]),[total,setTotal]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(""),[token,setToken]=useState("");
 const base=`/api/v1/plugins/com.selfcommand.tasknotes-webhook/projects/${projectId}/connections/${connectionId}`;
 async function request(path:string,method="GET",body?:unknown){const r=await fetch(path,{method,credentials:"include",headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error(r.status===409?"设置已变化，请刷新后重试。":"暂时无法连接，请稍后重试。");return r.json()}
 async function load(){const all=await request(`/api/v1/plugins/com.selfcommand.tasknotes-webhook/projects/${projectId}/connections`);const c=all.items.find((v:{id:string})=>v.id===connectionId);setMode(c.sync_mode??"off");setRevision(c.revision);const preview=await request(base+"/sync-preview");setItems(preview.items);setTotal(Number(preview.total));return c}
 useEffect(()=>{setToken("");void load().catch(e=>setError(e.message))},[base]);
 async function act(fn:()=>Promise<void>){setBusy(true);setError("");try{await fn()}catch(e){setError(e instanceof Error?e.message:"暂时无法操作。")}finally{setBusy(false)}}
 return <Card><CardHeader><CardTitle>双向任务同步</CardTitle><CardDescription>Paca 创建任务后，Obsidian 同步时生成任务笔记，无需先打卡。仅同步当前来源连接对应的项目。</CardDescription></CardHeader><CardContent className="grid gap-3"><Badge variant="secondary">{mode==="enabled"?"双向同步已启用":mode==="preview"?"正在核对首次同步清单":"双向同步未启用"}</Badge><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy||!canEdit} onClick={()=>act(async()=>{const c=await load();await request(base+"/sync-config","PUT",{mode:"preview",revision:c.revision,reverse_status_map:c.reverse_status_map??{}});await load()})}>准备任务清单</Button><Button variant="outline" disabled={busy} onClick={()=>act(async()=>{await load()})}>刷新清单</Button><Button disabled={busy||!canEdit||mode!=="preview"||!total} onClick={()=>act(async()=>{const c=await load();await request(base+"/sync-config","PUT",{mode:"enabled",revision:c.revision,reverse_status_map:c.reverse_status_map??{}});await load()})}>确认同步全部 {total} 个任务</Button>{mode==="enabled"&&<Button variant="outline" disabled={busy||!canEdit} onClick={()=>act(async()=>{const c=await load();await request(base+"/sync-config","PUT",{mode:"off",revision:c.revision,reverse_status_map:c.reverse_status_map??{}});await load()})}>暂停同步</Button>}</div><p className="text-sm text-muted-foreground">清单包括已完成和归档任务。状态对应关系使用上方配置；同名任务不会自动合并。</p>{items.map(item=><div key={item.sync_id} className="rounded-lg border p-3 text-sm"><strong>{item.snapshot.title||"任务"}</strong><p className="text-muted-foreground">{item.path||"下次同步时创建笔记"}{item.deleted?" · 已删除":""}</p>{item.warning&&<p className="text-destructive">{item.warning}</p>}</div>)}{total>items.length&&<p className="text-sm text-muted-foreground">展示前 {items.length} 条，共 {total} 条；同步包含全部任务。</p>}<Button variant="outline" disabled={busy||!canEdit} onClick={()=>act(async()=>{const r=await request(base+"/pairing","POST",{});setToken(r.token)})}>生成任务同步配对码</Button>{token&&<div className="rounded-lg border p-3"><p className="text-sm">配对码仅显示本次，可用于同一笔记库的电脑和手机。</p><Button variant="outline" onClick={()=>navigator.clipboard.writeText(token)}>复制配对码</Button><Button variant="ghost" onClick={()=>setToken("")}>已保存</Button></div>}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<span className="sr-only">设置版本 {revision}</span></CardContent></Card>
}
